/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan_barang;

/**
 *
 * @author nurai
 */
public class fmenu extends javax.swing.JFrame {

    /**
     * Creates new form fmenu
     */
    public fmenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMaster = new javax.swing.JMenu();
        miPegawai = new javax.swing.JMenuItem();
        miBarang = new javax.swing.JMenuItem();
        mTransaksi = new javax.swing.JMenu();
        miPenjualan = new javax.swing.JMenuItem();
        mLaporan = new javax.swing.JMenu();
        miLaporanStok = new javax.swing.JMenuItem();
        miLaporanPenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuraima");
        setSize(new java.awt.Dimension(1126, 600));

        jPanel1.setBackground(new java.awt.Color(37, 67, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT ANGIN RIBUT");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(388, 388, 388))
        );

        mMaster.setText("Master");

        miPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miPegawai.setText("Pegawai");
        miPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPegawaiActionPerformed(evt);
            }
        });
        mMaster.add(miPegawai);

        miBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miBarang.setText("Barang");
        miBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBarangActionPerformed(evt);
            }
        });
        mMaster.add(miBarang);

        jMenuBar1.add(mMaster);

        mTransaksi.setText("Transaksi");

        miPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miPenjualan.setText("Penjualan");
        miPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPenjualanActionPerformed(evt);
            }
        });
        mTransaksi.add(miPenjualan);

        jMenuBar1.add(mTransaksi);

        mLaporan.setText("Laporan");

        miLaporanStok.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLaporanStok.setText("Laporan Stok Barang");
        miLaporanStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLaporanStokActionPerformed(evt);
            }
        });
        mLaporan.add(miLaporanStok);

        miLaporanPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLaporanPenjualan.setText("Laporan Penjualan");
        miLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLaporanPenjualanActionPerformed(evt);
            }
        });
        mLaporan.add(miLaporanPenjualan);

        jMenuBar1.add(mLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPegawaiActionPerformed
        // TODO add your handling code here:
        fpegawai fb = new fpegawai();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miPegawaiActionPerformed

    private void miBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBarangActionPerformed
        // Untuk memanggil form barang pada menu:
        fbarang fb = new fbarang();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miBarangActionPerformed

    private void miPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPenjualanActionPerformed
        // TODO add your handling code here:
        fpenjualan fb = new fpenjualan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miPenjualanActionPerformed

    private void miLaporanStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLaporanStokActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_miLaporanStokActionPerformed

    private void miLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_miLaporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mLaporan;
    private javax.swing.JMenu mMaster;
    private javax.swing.JMenu mTransaksi;
    private javax.swing.JMenuItem miBarang;
    private javax.swing.JMenuItem miLaporanPenjualan;
    private javax.swing.JMenuItem miLaporanStok;
    private javax.swing.JMenuItem miPegawai;
    private javax.swing.JMenuItem miPenjualan;
    // End of variables declaration//GEN-END:variables
}
